services:
  squid:
    image: ${SQUID_CONTAINER_IMAGE:-ghcr.io/ophiosdev/squid:7}
    network_mode: host
    container_name: squid
    stop_grace_period: 1m
    volumes:
      - squid-cache:/var/cache/squid
      - ./squid.conf:/etc/squid/squid.conf
    cap_add:
      - NET_RAW
    restart: unless-stopped

volumes:
  squid-cache:
